pipeline {
    agent any
    stages{
        stage("Build") {
            steps {
                npm install
                npm run build
                echo "Build successful"
            }
        }
    }
}